/* ==================================================================
   MATERIAIS E RETRABALHOS
   Cadastro de materiais, etiquetas FQ 099, fotos, painel e sincronização.
   ================================================================== */
/* ===== Materiais (refugo e retrabalho) ===== */
var MAT_PADRAO=['GG25','GG30','GGG40','GGG50','GGG60'];
/* "GG 25", "gg25" e "GG-25" passam a ser o mesmo material: GG25 */
function matNorm(m){return String(m||'').toUpperCase().replace(/[\s\-_.]+/g,'')}
function matShow(m){var n=matNorm(m);return(!n||n==='SEMMATERIAL')?'NÃO INFORMADO':n}
function matList(){var s={};((typeof cadastros!=='undefined'&&cadastros&&Array.isArray(cadastros.materiais)&&cadastros.materiais.length)?cadastros.materiais:MAT_PADRAO).forEach(function(m){m=matNorm(m);if(m)s[m]=1});((typeof cadastros!=='undefined'&&cadastros&&cadastros.pecas)||[]).forEach(function(p){var m0=String(p.material||'').trim().toUpperCase(),m=matNorm(m0);if(m&&m0!=='SEM MATERIAL')s[m]=1});return Object.keys(s).sort()}
function selSet(id,v){var e=document.getElementById(id);if(!e)return;v=String(v||'').trim();if(v&&![].some.call(e.options,function(o){return o.value===v})){var o=document.createElement('option');o.value=o.textContent=v;e.appendChild(o)}e.value=v}
function selFill(id,list,first){var e=document.getElementById(id);if(!e)return;var cur=e.value;e.innerHTML='<option value="">'+first+'</option>'+list.map(function(m){return '<option value="'+esc(m)+'">'+esc(m)+'</option>'}).join('');if(cur)selSet(id,cur)}
function ltMatPop(){selFill('material',matList(),'Selecione')}
function ltMatSet(v){ltMatPop();selSet('material',matNorm(v))}
function prodOf(cod,cli){try{return(window.__BUSCAR_PRODUTO_OFICIAL__&&window.__BUSCAR_PRODUTO_OFICIAL__(cod))||findPeca(cli||'',cod)}catch(e){return null}}
function ltMatFill(){var m=document.getElementById('material');if(!m||m.value)return;var p=prodOf((document.getElementById('codigo')||{}).value,'');if(p&&p.material)ltMatSet(p.material)}
function matRec(r){var m=matNorm(val(r,'material'));if(m&&m!=='SEMMATERIAL')return m;var p=prodOf(val(r,'codigo'),'');return matShow(p&&p.material)}
function cadMatLoad(){var e=document.getElementById('cadMatTxt');if(e)e.value=matList().join('\n')}
function salvarMateriais(){var a=[...new Set(String(document.getElementById('cadMatTxt').value||'').split(/\n|,|;/).map(function(x){return matNorm(x)}).filter(Boolean))];cadastros.materiais=a;try{saveCad()}catch(e){try{localStorage.setItem(CADKEY,JSON.stringify(cadastros))}catch(x){}}ltMatPop();alert('Materiais salvos ('+a.length+').')}
(function(){function b(){var c=document.getElementById('codigo'),k=document.getElementById('cliente');if(c)c.addEventListener('input',function(){setTimeout(ltMatFill,500)});if(k)k.addEventListener('change',function(){setTimeout(ltMatFill,300)});try{ltMatPop()}catch(e){}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',b);else b()})();

/* ===== Retrabalhos (etiqueta FQ 099 rev01) ===== */
var RT_ST=['Aguardando retrabalho','Em retrabalho','Retrabalho concluído'],rtFt={a:[],d:[],rem:[]};
function rtRaw(){try{var a=JSON.parse(localStorage.getItem(KEY+'_retrabalhos')||'[]'),ch=false;a.forEach(function(r){if(!r.ts){r.ts=Date.now();ch=true}});if(ch)localStorage.setItem(KEY+'_retrabalhos',JSON.stringify(a));return a}catch(e){return[]}}
function rtLoad(){return rtRaw().filter(function(r){return !r.del})}
function rtStore(a){localStorage.setItem(KEY+'_retrabalhos',JSON.stringify(a))}
function rtPend(){try{return JSON.parse(localStorage.getItem(KEY+'_rt_pend')||'[]')}catch(e){return[]}}
function rtPendAdd(id){localStorage.setItem(KEY+'_rt_pend',JSON.stringify([...new Set(rtPend().concat(id))]))}
function rtPut(r){r.ts=Date.now();var a=rtRaw(),i=a.findIndex(function(x){return x.id===r.id});if(i>=0)a[i]=r;else a.unshift(r);rtStore(a);rtPendAdd(r.id);rtFlush();rtSyncLbl()}
/* --- sincronização entre computadores (Firestore: apps/controleRefugos2026/retrabalhos) --- */
var rtUnsub=null,rtFlushing=false;
function rtOnline(){try{return typeof firebaseOnlineConnected!=='undefined'&&firebaseOnlineConnected&&typeof firebaseDbOnline!=='undefined'&&!!firebaseDbOnline&&localStorage.getItem(FIREBASE_SYNC_KEY)!=='false'}catch(e){return false}}
function rtCol(){return firebaseRoot().collection('retrabalhos')}
async function rtFlush(){if(rtFlushing||!rtOnline())return;var p=rtPend();if(!p.length)return;rtFlushing=true;try{var raw=rtRaw(),left=[];for(var i=0;i<p.length;i++){var r=raw.find(function(x){return x.id===p[i]});if(!r)continue;try{await rtCol().doc(r.id).set(fsSanitize(r))}catch(e){left.push(p[i]);console.error('retrabalho: envio',e)}}localStorage.setItem(KEY+'_rt_pend',JSON.stringify(left))}finally{rtFlushing=false;rtSyncLbl()}}
function rtUnlisten(){if(rtUnsub){try{rtUnsub()}catch(e){}rtUnsub=null}}
function rtListen(){rtUnlisten();if(!rtOnline())return;rtUnsub=rtCol().onSnapshot(function(snap){if(snap.metadata&&snap.metadata.hasPendingWrites)return;var by={},seen={},ch=false;rtRaw().forEach(function(r){by[r.id]=r});
snap.docs.forEach(function(d){var rm=fsDesanitize(d.data());if(!rm||!rm.id)return;seen[rm.id]=1;var l=by[rm.id];if(!l||(rm.ts||0)>(l.ts||0)){by[rm.id]=rm;ch=true}else if((l.ts||0)>(rm.ts||0))rtPendAdd(l.id)});
Object.keys(by).forEach(function(id){if(!seen[id])rtPendAdd(id)});
if(ch){rtStore(Object.keys(by).map(function(k){return by[k]}).sort(function(a,b){return String(b.dt||'').localeCompare(String(a.dt||''))||(b.ts||0)-(a.ts||0)}));rtRefreshView()}rtFlush();rtSyncLbl()},function(e){console.error('Escuta retrabalhos',e)})}
function rtRefreshView(){var l=document.getElementById('rtLista'),p=document.getElementById('rtPainel');if(l&&l.offsetParent)rtLista();if(p&&p.offsetParent)rtPainel()}
function rtSyncLbl(){var e=document.getElementById('rtSync');if(!e)return;var n=rtPend().length;e.innerHTML=rtOnline()?'☁ <b>Sincronizado com a nuvem</b> — as etiquetas aparecem em todos os computadores conectados.'+(n?' ⏳ '+n+' alteração(ões) aguardando envio.':''):'💾 <b>Salvo somente neste aparelho.</b> Conecte o sistema online (Dados e backup) para compartilhar com os outros computadores.'+(n?' ('+n+' pendente(s) de envio)':'')}
function rtV(id){var e=document.getElementById(id);return e?String(e.value||'').trim():''}
function rtSet(id,v){var e=document.getElementById(id);if(e)e.value=v==null?'':v}
function rtNow(){var d=new Date();return ('0'+d.getHours()).slice(-2)+':'+('0'+d.getMinutes()).slice(-2)}
function rtBd(st){var c=st===RT_ST[2]?'#16a34a':st===RT_ST[1]?'#2563eb':'#d97706';return '<span class="rt-bd" style="background:'+c+'">'+esc(st)+'</span>'}
function rtDur(r){if(!r.hi||!r.hf)return null;var a=r.hi.split(':'),b=r.hf.split(':'),m=(+b[0]*60+ +b[1])-(+a[0]*60+ +a[1]);if(m<0)m+=1440;return m}
function rtAge(r){var f=r.st===RT_ST[2]?(r.df||anaToday()):anaToday();return Math.max(0,anaDays(r.dt,f))}
function rtMatOf(r){var m=matNorm(r.mat);if(m&&m!=='SEMMATERIAL')return m;var p=prodOf(r.cod,'');return matShow(p&&p.material)}
function rtLocOf(r){return String(r.locR||r.locE||'').trim().toUpperCase()||'NÃO INFORMADO'}
function rtTab(k){document.querySelectorAll('#retrabalho .rt-tab').forEach(function(b){b.classList.toggle('on',b.dataset.rt===k)});['lancar','painel','lista'].forEach(function(x){var e=document.getElementById('rt'+x.charAt(0).toUpperCase()+x.slice(1));if(e)e.style.display=x===k?'':'none'});if(k==='painel')rtPainel();if(k==='lista')rtLista()}
window.rtInit=function(){var L=function(id,a){var e=document.getElementById(id);if(e)e.innerHTML=a.map(function(x){return '<option value="'+esc(x)+'">'}).join('')};
var c=(typeof cadastros!=='undefined'&&cadastros)||{},A=rtLoad();L('rtCliList',(c.clientes||[]).filter(function(x){return String(x).toUpperCase()!=='SEM CLIENTE CADASTRO'}));L('rtRespList',c.responsaveis||[]);
L('rtLocList',[...new Set(A.map(rtLocOf).filter(function(x){return x!=='NÃO INFORMADO'}))].sort());selFill('rtMat',matList(),'Selecione');
if(!rtV('rtDt'))rtSet('rtDt',anaToday());if(!rtV('rtPb')){rtSet('rtPb',anaToday());rtSet('rtPa',anaToday().slice(0,8)+'01')}if(rtOnline()&&!rtUnsub)rtListen();rtFlush();rtSyncLbl()}
function rtBusca(){var h=document.getElementById('rtHint');try{var cod=rtV('rtCod');if(!cod){h.textContent='';return}var p=prodOf(cod,rtV('rtCli'));
if(!rtV('rtCli')){var cnt={};(typeof data!=='undefined'?data:[]).forEach(function(r){if(String(val(r,'codigo')).trim()===cod){var k=String(val(r,'cliente')||'').trim();if(k&&k.toUpperCase()!=='SEM CLIENTE CADASTRO')cnt[k]=(cnt[k]||0)+1}});var ks=Object.keys(cnt).sort(function(a,b){return cnt[b]-cnt[a]});if(ks.length)rtSet('rtCli',ks[0]);else if(p&&p.cliente)rtSet('rtCli',p.cliente)}
if(p){rtSet('rtProd',p.descricao);if(p.material)selSet('rtMat',matNorm(p.material));h.textContent='✔ Produto encontrado no cadastro dos refugos'+(p.planta?' — planta '+p.planta:'')+(p.material?' — material '+p.material:'')+'.'}else h.textContent='Código não encontrado no cadastro; preencha manualmente.'}catch(e){}}
function rtFotoRender(){['a','d'].forEach(function(k){var b=document.getElementById('rtFp'+k);if(b)b.innerHTML=rtFt[k].map(function(f,i){return '<div class="fp"><img src="'+f.url+'" alt="foto" onclick="rtLb(rtFt.'+k+'['+i+'].url)"><button type="button" title="Remover" onclick="rtFotoDel(\''+k+'\','+i+')">×</button></div>'}).join('')})}
function rtFotoAdd(k,inp){var fs=[].slice.call(inp.files||[]);inp.value='';(async function(){for(var i=0;i<fs.length;i++){if(rtFt[k].length>=FOTO_MAX)break;try{var u=await fotoComprimir(fs[i]);rtFt[k].push({id:'rt_'+Date.now().toString(36)+Math.random().toString(36).slice(2,6),url:u,novo:true})}catch(e){alert('Não foi possível ler a foto.')}}rtFotoRender()})()}
function rtFotoDel(k,i){var f=rtFt[k][i];if(f&&!f.novo)rtFt.rem.push(f.id);rtFt[k].splice(i,1);rtFotoRender()}
function rtLb(url){var d=document.createElement('div');d.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.92);z-index:99999;overflow:auto;padding:14px;text-align:center;cursor:zoom-out';d.onclick=function(){d.remove()};d.innerHTML=(Array.isArray(url)?url:[url]).map(function(u){return typeof u==='string'?'<img src="'+u+'" style="max-width:100%;margin:6px;border-radius:8px">':'<div style="color:#fff;font-weight:800;margin:14px 0 4px">'+esc(u.t)+'</div>'+u.f.map(function(x){return '<img src="'+x+'" style="max-width:100%;margin:6px;border-radius:8px">'}).join('')}).join('');document.body.appendChild(d)}
async function rtVer(id){var r=rtLoad().find(function(x){return x.id===id});if(!r)return;var g=async function(ids){var o=[];for(var i=0;i<(ids||[]).length;i++){var u=await fotoGet(ids[i]);if(u)o.push(u)}return o};var a=await g(r.fa),d=await g(r.fd);if(!a.length&&!d.length){alert('Esta etiqueta não tem fotos.');return}rtLb([{t:'ANTES do retrabalho',f:a},{t:'DEPOIS do retrabalho',f:d}])}
function rtClear(){['rtId','rtCod','rtCli','rtProd','rtCodCli','rtOf','rtQtd','rtMat','rtRespE','rtLocE','rtMot','rtHi','rtHf','rtDi','rtDf','rtOk','rtRf','rtRespR','rtLocR','rtObs'].forEach(function(i){rtSet(i,'')});rtSet('rtSt',RT_ST[0]);rtSet('rtDt',anaToday());rtFt={a:[],d:[],rem:[]};rtFotoRender();document.getElementById('rtHint').textContent=''}
async function rtSave(){var r={id:rtV('rtId')||String(Date.now()),dt:rtV('rtDt'),cod:rtV('rtCod'),cli:rtV('rtCli'),prod:rtV('rtProd'),codCli:rtV('rtCodCli'),of:rtV('rtOf'),qtd:Number(rtV('rtQtd'))||0,mat:rtV('rtMat'),mot:rtV('rtMot'),respE:rtV('rtRespE'),locE:rtV('rtLocE'),st:rtV('rtSt')||RT_ST[0],hi:rtV('rtHi'),hf:rtV('rtHf'),di:rtV('rtDi'),df:rtV('rtDf'),qOk:rtV('rtOk')===''?null:(Number(rtV('rtOk'))||0),qRef:rtV('rtRf')===''?null:(Number(rtV('rtRf'))||0),respR:rtV('rtRespR'),locR:rtV('rtLocR'),obs:rtV('rtObs')};
var m=document.getElementById('rtMsg');if(!r.dt||(!r.cod&&!r.prod)||r.qtd<=0){m.style.color='#dc2626';m.textContent='Informe a data, o código ou produto e a quantidade.';return}
if((r.qOk||0)+(r.qRef||0)>r.qtd){m.style.color='#dc2626';m.textContent='Peças OK + refugadas ('+((r.qOk||0)+(r.qRef||0))+') passa da quantidade da etiqueta ('+r.qtd+').';return}
if(r.st!==RT_ST[0]&&!r.di)r.di=anaToday();if(r.st===RT_ST[2]&&!r.df)r.df=anaToday();
for(var k of ['a','d']){var ids=[];for(var f of rtFt[k]){ids.push(f.id);if(f.novo){await fotoLocalPut({id:f.id,url:f.url,synced:false});fotoPushRemote({id:f.id,url:f.url}).catch(function(){})}}r['f'+k]=ids}
for(var x of rtFt.rem)await fotoApagarRemoto(x);
rtPut(r);m.style.color='#16a34a';m.textContent='✔ Etiqueta salva ('+rtLoad().length+' no total).';rtClear();window.rtInit()}
async function rtEdit(id){var r=rtLoad().find(function(x){return x.id===id});if(!r)return;rtTab('lancar');window.rtInit();rtSet('rtId',r.id);rtSet('rtDt',r.dt);rtSet('rtCod',r.cod);rtSet('rtCli',r.cli);rtSet('rtProd',r.prod);rtSet('rtCodCli',r.codCli);rtSet('rtOf',r.of);rtSet('rtQtd',r.qtd);selSet('rtMat',matNorm(r.mat));rtSet('rtMot',r.mot);rtSet('rtRespE',r.respE);rtSet('rtLocE',r.locE);rtSet('rtSt',r.st);rtSet('rtHi',r.hi);rtSet('rtHf',r.hf);rtSet('rtDf',r.df);rtSet('rtRespR',r.respR);rtSet('rtLocR',r.locR);rtSet('rtObs',r.obs);
rtSet('rtDi',r.di);rtSet('rtOk',r.qOk==null?'':r.qOk);rtSet('rtRf',r.qRef==null?'':r.qRef);var dd=document.querySelector('#rtLancar details');if(dd)dd.open=true;document.getElementById('rtMsg').textContent='Editando etiqueta — salve para atualizar.';window.scrollTo({top:0,behavior:'smooth'});rtFt={a:[],d:[],rem:[]};for(var k of ['a','d']){for(var id2 of (r['f'+k]||[])){var u=await fotoGet(id2);if(u)rtFt[k].push({id:id2,url:u,novo:false})}}rtFotoRender()}
async function rtDel(id){if(!confirm('Excluir esta etiqueta de retrabalho (e suas fotos)?'))return;var r=rtLoad().find(function(x){return x.id===id});if(r)for(var x of (r.fa||[]).concat(r.fd||[]))await fotoApagarRemoto(x);rtPut({id:id,del:true,dt:r?r.dt:''});rtLista()}
function rtAdv(id,st){var a=rtLoad(),r=a.find(function(x){return x.id===id});if(!r)return;
if(st===RT_ST[2]){var ok=prompt('Quantas peças deram CERTO? (etiqueta com '+r.qtd+' peças)',r.qOk!=null?r.qOk:r.qtd);if(ok===null)return;ok=Number(String(ok).replace(',','.'));if(isNaN(ok)||ok<0||ok>r.qtd){alert('Valor inválido.');return}
var rf=prompt('Quantas peças foram REFUGADAS no retrabalho?',Math.max(0,r.qtd-ok));if(rf===null)return;rf=Number(String(rf).replace(',','.'));if(isNaN(rf)||rf<0||ok+rf>r.qtd){alert('Peças OK + refugadas não pode passar de '+r.qtd+'.');return}r.qOk=ok;r.qRef=rf}
r.st=st;if(st!==RT_ST[0]&&!r.di)r.di=anaToday();if(st===RT_ST[1]&&!r.hi)r.hi=rtNow();if(st===RT_ST[2]){if(!r.hi)r.hi=rtNow();r.hf=rtNow();r.df=anaToday()}rtPut(r);rtLista()}
function rtLista(){var q=anaNorm(rtV('rtQ')),fs=rtV('rtFs'),a=rtLoad().filter(function(r){return(!fs||r.st===fs)&&(!q||anaNorm([r.cli,r.cod,r.codCli,r.of,r.prod,r.mot,r.respE,r.respR,r.mat,r.locE,r.locR].join(' ')).indexOf(q)>=0)});
a.sort(function(x,y){return (x.st===RT_ST[2])-(y.st===RT_ST[2])||String(y.dt).localeCompare(String(x.dt))});
var rows=a.slice(0,200).map(function(r){var ag=rtAge(r),late=r.st!==RT_ST[2]&&ag>3,nf=(r.fa||[]).length+(r.fd||[]).length;return '<tr><td>'+anaBR(r.dt)+'</td><td>'+esc(r.cli)+'</td><td>'+esc(r.cod)+'<br><span class="hint">'+esc(r.prod)+'</span></td><td>'+esc(r.of)+'</td><td>'+r.qtd+'</td><td>'+esc(rtMatOf(r))+'</td><td>'+esc(rtLocOf(r))+'</td><td>'+esc(r.mot)+'</td><td>'+rtBd(r.st)+'</td><td>'+(r.di?anaBR(r.di):'—')+' → '+(r.df?anaBR(r.df):'—')+'</td><td>'+(r.qOk!=null?r.qOk:'—')+' ✔ / '+(r.qRef!=null?r.qRef:'—')+' ✖</td><td style="color:'+(late?'#dc2626':'inherit')+';font-weight:'+(late?800:400)+'">'+ag+' d'+(late?' ⚠':'')+'</td><td class="rt-act">'+(r.st===RT_ST[0]?'<button onclick="rtAdv(\''+r.id+'\',RT_ST[1])">▶ Iniciar</button>':'')+(r.st!==RT_ST[2]?'<button onclick="rtAdv(\''+r.id+'\',RT_ST[2])">✔ Concluir</button>':'')+(nf?'<button onclick="rtVer(\''+r.id+'\')">📷 '+nf+'</button>':'')+'<button onclick="rtEdit(\''+r.id+'\')">✏</button><button onclick="rtDel(\''+r.id+'\')">🗑</button></td></tr>'}).join('');
document.getElementById('rtTbl').innerHTML='<table><thead><tr><th>Emissão</th><th>Cliente</th><th>Produto</th><th>OF</th><th>Qtd.</th><th>Material</th><th>Máquina</th><th>Motivo</th><th>Status</th><th>Início → Fim</th><th>OK / Refugo</th><th>Idade</th><th>Ações</th></tr></thead><tbody>'+(rows||'<tr><td colspan="13">Nenhuma etiqueta encontrada.</td></tr>')+'</tbody></table>'}
function rtPreset(k){var td=anaToday(),d=new Date(),y=d.getFullYear(),m=d.getMonth(),a='',b=td;if(k==='7')a=anaAdd(td,-6);else if(k==='30')a=anaAdd(td,-29);else if(k==='mes')a=anaFmtD(new Date(y,m,1));else if(k==='ant'){a=anaFmtD(new Date(y,m-1,1));b=anaFmtD(new Date(y,m,0))}else if(k==='ano')a=anaFmtD(new Date(y,0,1));else{a='';b=''}rtSet('rtPa',a);rtSet('rtPb',b);rtPainel()}
function rtLimpar(){['rtFm','rtFl','rtFc','rtFst'].forEach(function(i){rtSet(i,'')});rtPainel()}
function rtPick(id,v){rtSet(id,v);rtPainel()}
function rtPainel(){var all=rtLoad();selFill('rtFm',[...new Set(all.map(rtMatOf))].sort(),'Todos');selFill('rtFl',[...new Set(all.map(rtLocOf))].sort(),'Todas');selFill('rtFc',[...new Set(all.map(function(r){return r.cli||'—'}))].sort(),'Todos');
var a0=rtV('rtPa'),b0=rtV('rtPb'),fm=rtV('rtFm'),fl=rtV('rtFl'),fc=rtV('rtFc'),fs=rtV('rtFst'),met=rtV('rtMet')||'q';
var flt=function(r){return(!fm||rtMatOf(r)===fm)&&(!fl||rtLocOf(r)===fl)&&(!fc||(r.cli||'—')===fc)&&(!fs||r.st===fs)},A=all.filter(function(r){return(!a0||r.dt>=a0)&&(!b0||r.dt<=b0)&&flt(r)}),
len=(a0&&b0)?Math.max(1,anaDays(a0,b0)+1):0,P=len?all.filter(function(r){return r.dt>=anaAdd(a0,-len)&&r.dt<=anaAdd(a0,-1)&&flt(r)}):[];
var val_=function(r){return met==='q'?r.qtd:1},sm=function(L){return L.reduce(function(s,r){return s+val_(r)},0)},u=met==='q'?'peças':'etiquetas';
var n=A.length,pc=A.reduce(function(s,r){return s+r.qtd},0),pp=P.reduce(function(s,r){return s+r.qtd},0),by=function(s){return A.filter(function(r){return r.st===s})},cc=by(RT_ST[2]),rec=A.reduce(function(s,r){return s+(r.qOk||0)},0),rfr=A.reduce(function(s,r){return s+(r.qRef||0)},0),di_=A.filter(function(r){return r.di&&r.df}),dd_=di_.length?di_.reduce(function(s,r){return s+Math.max(0,anaDays(r.di,r.df))},0)/di_.length:0,late=A.filter(function(r){return r.st!==RT_ST[2]&&rtAge(r)>3}),
lt=cc.length?cc.reduce(function(s,r){return s+rtAge(r)},0)/cc.length:0,du=A.map(rtDur).filter(function(x){return x!=null}),dm=du.length?du.reduce(function(s,x){return s+x},0)/du.length:0;
var hm_=function(m){return Math.floor(m/60)+'h '+('0'+Math.round(m%60)).slice(-2)+'min'};
var dl=function(c,p){return p?'<small style="color:'+(c>p?'#dc2626':'#16a34a')+'">'+(c>p?'▲ +':'▼ ')+fmt(Math.abs((c-p)/p*100))+'% vs período anterior</small>':'<small>&nbsp;</small>'};
var K=function(v,l,c,s){return '<div class="rt-kpi" style="--c:'+(c||'#ff5a1a')+'"><span>'+l+'</span><b style="color:'+(c||'inherit')+'">'+v+'</b>'+(s||'<small>&nbsp;</small>')+'</div>'};
document.getElementById('rtKpis').innerHTML='<div class="rt-kpis">'+K(n,'Etiquetas','#ff5a1a',dl(n,P.length))+K(fmt(pc),'Peças em retrabalho','#eab308',dl(pc,pp))+K(fmt(rec),'Peças OK (recuperadas)','#16a34a','<small>'+(pc?fmt(rec/pc*100)+'% das peças':'&nbsp;')+'</small>')+K(fmt(rfr),'Refugadas no retrabalho',rfr?'#dc2626':'#64748b','<small>'+(pc?fmt(rfr/pc*100)+'% das peças':'&nbsp;')+'</small>')+K(by(RT_ST[0]).length,'Aguardando','#d97706')+K(by(RT_ST[1]).length,'Em retrabalho','#2563eb')+K(late.length,'Atrasadas (+3 dias)',late.length?'#dc2626':'#64748b')+K(cc.length?fmt(lt)+' d':'—','Prazo médio (emissão → fim)','#7c3aed')+K(di_.length?fmt(dd_)+' d':'—','Duração média (início → fim)','#0ea5e9')+K(du.length?hm_(dm):'—','Tempo médio de execução','#0891b2')+'</div>';
function agg(fn,w){var m={};A.forEach(function(r){var k=fn(r)||'—';m[k]=(m[k]||0)+(w?w(r):val_(r))});return Object.keys(m).map(function(k){return[k,m[k]]}).sort(function(x,y){return y[1]-x[1]})}
var tot=sm(A),tm=agg(rtMatOf),tl=agg(rtLocOf),tmo=agg(function(r){return r.mot.slice(0,60)}),ins=[];
var pq=0,rm={};try{(typeof data!=='undefined'?data:[]).forEach(function(r){var d=anaISO(r);if(!d||(a0&&d<a0)||(b0&&d>b0))return;if(fm&&matRec(r)!==fm)return;if(fc&&String(val(r,'cliente')||'—')!==fc)return;var q=qty(r)||0;pq+=q;var k=d.slice(0,7);rm[k]=(rm[k]||0)+q})}catch(e){}
if(tm.length&&tot)ins.push('Material <b>'+esc(tm[0][0])+'</b> concentra <b>'+fmt(tm[0][1]/tot*100)+'%</b> das '+u+'.');
if(tl.length&&tot)ins.push('Máquina/local <b>'+esc(tl[0][0])+'</b> lidera com <b>'+fmt(tl[0][1])+'</b> '+u+' ('+fmt(tl[0][1]/tot*100)+'%).');
if(tmo.length&&tot)ins.push('Principal motivo: <b>'+esc(tmo[0][0])+'</b> ('+fmt(tmo[0][1]/tot*100)+'%).');
if(pc+pq>0)ins.push('Entre as peças com problema no período, <b>'+fmt(pc/(pc+pq)*100)+'%</b> foram para retrabalho ('+fmt(pc)+') e <b>'+fmt(pq/(pc+pq)*100)+'%</b> viraram refugo ('+fmt(pq)+').');
if(rec+rfr>0)ins.push('No retrabalho: <b>'+fmt(rec/(rec+rfr)*100)+'%</b> das peças deram certo ('+fmt(rec)+') e <b>'+fmt(rfr/(rec+rfr)*100)+'%</b> foram refugadas ('+fmt(rfr)+').');
var old=A.filter(function(r){return r.st!==RT_ST[2]}).sort(function(x,y){return rtAge(y)-rtAge(x)});if(old[0])ins.push('Etiqueta aberta mais antiga: <b>'+esc(old[0].cod||old[0].prod)+'</b> — OF '+esc(old[0].of||'—')+', há <b>'+rtAge(old[0])+' dias</b>.');
document.getElementById('rtIns').innerHTML=ins.length?'<div class="panel" style="border-left:6px solid #facc15"><h3>💡 Leitura rápida</h3>'+ins.map(function(x){return '<div style="margin:5px 0">'+x+'</div>'}).join('')+'</div>':'';
function bars(ti,e,sel,ff,wide){e=e.slice(0,8);ff=ff||fmt;var mx=e.length?e[0][1]:1;return '<div class="panel'+(wide?' rt-wide':'')+'"><h3>'+ti+'</h3>'+(sel?'<div class="hint" style="margin:-4px 0 6px">Toque numa barra para filtrar</div>':'')+(e.map(function(x){return '<div class="'+(sel?'rt-pick':'')+'" '+(sel?'data-v="'+esc(x[0])+'" onclick="rtPick(\''+sel+'\',this.dataset.v)"':'')+' style="margin:7px 0;font-size:13px"><div style="display:flex;justify-content:space-between;gap:8px"><span>'+esc(x[0])+'</span><b>'+ff(x[1])+'</b></div><div class="rt-bar"><i style="width:'+(x[1]/mx*100)+'%"></i></div></div>'}).join('')||'<div class="hint">Sem dados.</div>')+'</div>'}
var cs=RT_ST.map(function(s){return by(s).length}),co=['#d97706','#2563eb','#16a34a'],off=0,seg=n?cs.map(function(v,i){var l=v/n*100,s='<circle r="15.9155" cx="21" cy="21" fill="none" stroke="'+co[i]+'" stroke-width="7" stroke-dasharray="'+l+' '+(100-l)+'" stroke-dashoffset="'+(25-off)+'"/>';off+=l;return s}).join(''):'';
var donut='<div class="panel"><h3>Status das etiquetas</h3><div style="display:flex;align-items:center;gap:18px;flex-wrap:wrap"><svg viewBox="0 0 42 42" width="140" height="140"><circle r="15.9155" cx="21" cy="21" fill="none" stroke="rgba(127,127,127,.2)" stroke-width="7"/>'+seg+'<text x="21" y="23" text-anchor="middle" font-size="8" font-weight="800" fill="currentColor">'+n+'</text></svg><div style="font-size:13px">'+RT_ST.map(function(s,i){return '<div style="margin:4px 0"><span style="display:inline-block;width:10px;height:10px;border-radius:3px;background:'+co[i]+'"></span> '+s+': <b>'+cs[i]+'</b></div>'}).join('')+'</div></div></div>';
function cols(mapA,mapB,la,lb){var ks=[...new Set(Object.keys(mapA).concat(Object.keys(mapB||{})))].sort().slice(-12),mx=Math.max.apply(null,ks.map(function(k){return Math.max(mapA[k]||0,(mapB||{})[k]||0)}).concat([1])),bw=100/Math.max(ks.length,1);
if(!ks.length)return '<div class="hint">Sem dados.</div>';return '<svg viewBox="0 0 100 54" style="width:100%;max-height:230px">'+ks.map(function(k,i){var h1=(mapA[k]||0)/mx*34,h2=((mapB||{})[k]||0)/mx*34,x=i*bw,two=!!mapB,w=two?bw*.38:bw*.64;return '<rect x="'+(x+(two?bw*.1:bw*.18))+'" y="'+(44-h1)+'" width="'+w+'" height="'+h1+'" rx="1" fill="#facc15"/>'+(two?'<rect x="'+(x+bw*.52)+'" y="'+(44-h2)+'" width="'+w+'" height="'+h2+'" rx="1" fill="#94a3b8"/>':'')+'<text x="'+(x+(two?bw*.29:bw/2))+'" y="'+(42-h1)+'" text-anchor="middle" font-size="3" fill="currentColor">'+fmt(mapA[k]||0)+'</text>'+(two?'<text x="'+(x+bw*.71)+'" y="'+(42-h2)+'" text-anchor="middle" font-size="3" fill="currentColor">'+fmt((mapB||{})[k]||0)+'</text>':'')+'<text x="'+(x+bw/2)+'" y="50" text-anchor="middle" font-size="3.2" fill="currentColor">'+k.slice(5)+'/'+k.slice(2,4)+'</text>'}).join('')+'</svg>'+(mapB?'<div style="font-size:12px"><span style="color:#d4a90a">■</span> '+la+' &nbsp; <span style="color:#94a3b8">■</span> '+lb+'</div>':'')}
var mm={};A.forEach(function(r){var k=r.dt.slice(0,7);mm[k]=(mm[k]||0)+val_(r)});var rq={};A.forEach(function(r){var k=r.dt.slice(0,7);rq[k]=(rq[k]||0)+r.qtd});
var evo='<div class="panel"><h3>Evolução mensal ('+u+')</h3>'+cols(mm)+'</div>',vs='<div class="panel"><h3>Retrabalho × Refugo (peças por mês)</h3>'+cols(rq,rm,'Retrabalho','Refugo')+'</div>';
var tmk=tm.slice(0,6).map(function(x){return x[0]}),tlk=tl.slice(0,8).map(function(x){return x[0]}),hm={},hmx=1;A.forEach(function(r){var k=rtLocOf(r)+'|'+rtMatOf(r);hm[k]=(hm[k]||0)+val_(r);if(hm[k]>hmx)hmx=hm[k]});
var heat='<div class="panel rt-wide"><h3>Mapa de calor: máquina × material ('+u+')</h3><div class="tablewrap"><table><thead><tr><th>Máquina \\ Material</th>'+tmk.map(function(m){return '<th style="text-align:center">'+esc(m)+'</th>'}).join('')+'</tr></thead><tbody>'+(tlk.map(function(l){return '<tr><td><b>'+esc(l)+'</b></td>'+tmk.map(function(m){var v=hm[l+'|'+m]||0;return '<td style="text-align:center;background:rgba(255,90,26,'+(v?(.12+v/hmx*.7):0).toFixed(2)+');font-weight:'+(v?700:400)+'">'+(v?fmt(v):'·')+'</td>'}).join('')+'</tr>'}).join('')||'<tr><td>Sem dados.</td></tr>')+'</tbody></table></div></div>';
var ac=0,par='<div class="panel rt-wide"><h3>Pareto por motivo ('+u+')</h3><div class="tablewrap"><table><thead><tr><th>Motivo</th><th>'+u+'</th><th>%</th><th>% acum.</th></tr></thead><tbody>'+(tmo.slice(0,8).map(function(x){ac+=x[1];return '<tr><td>'+esc(x[0])+'<div class="rt-bar"><i style="width:'+(x[1]/tot*100)+'%"></i></div></td><td>'+fmt(x[1])+'</td><td>'+fmt(x[1]/tot*100)+'%</td><td>'+fmt(ac/tot*100)+'%</td></tr>'}).join('')||'<tr><td colspan="4">Sem dados.</td></tr>')+'</tbody></table></div></div>';
var tq={},tc={};A.forEach(function(r){var d=rtDur(r);if(d==null)return;var k=rtLocOf(r);tq[k]=(tq[k]||0)+d;tc[k]=(tc[k]||0)+1});var te=Object.keys(tq).map(function(k){return[k,tq[k]/tc[k]]}).sort(function(x,y){return y[1]-x[1]});
var ag=[['0–1 dia',0,1],['2–3 dias',2,3],['4–7 dias',4,7],['+7 dias',8,9999]].map(function(b){return[b[0],A.filter(function(r){var g=rtAge(r);return r.st!==RT_ST[2]&&g>=b[1]&&g<=b[2]}).length]});
var ab='<div class="panel rt-wide"><h3>Etiquetas abertas mais antigas</h3><div class="tablewrap"><table><thead><tr><th>Produto</th><th>Cliente</th><th>Máquina</th><th>Qtd.</th><th>Status</th><th>Idade</th><th></th></tr></thead><tbody>'+(old.slice(0,8).map(function(r){var g=rtAge(r);return '<tr><td>'+esc(r.cod)+'<br><span class="hint">'+esc(r.prod)+'</span></td><td>'+esc(r.cli)+'</td><td>'+esc(rtLocOf(r))+'</td><td>'+r.qtd+'</td><td>'+rtBd(r.st)+'</td><td style="color:'+(g>3?'#dc2626':'inherit')+';font-weight:700">'+g+' d</td><td class="rt-act"><button onclick="rtEdit(\''+r.id+'\')">✏ Abrir</button></td></tr>'}).join('')||'<tr><td colspan="7">Nenhuma etiqueta aberta no filtro. 🎉</td></tr>')+'</tbody></table></div></div>';
document.getElementById('rtCharts').innerHTML=donut+vs+evo+bars('Por material ('+u+')',tm,'rtFm')+heat+bars('Por máquina / local ('+u+')',tl,'rtFl')+bars('Por cliente ('+u+')',agg(function(r){return r.cli||'—'}),'rtFc')+par+bars('Por produto ('+u+')',agg(function(r){return (r.cod?r.cod+' - ':'')+r.prod}))+bars('Por responsável ('+u+')',agg(function(r){return r.respR||r.respE}))+bars('Tempo médio de execução por máquina',te,null,hm_)+bars('Abertas por idade (etiquetas)',ag)+ab}
function rtCsv(){var a=rtLoad(),h=['Emissão','Cód. sistema','Cliente','Produto','Cód. cliente','OF','Qtd','Material','Motivo','Resp. emissão','Local emissão','Status','Hora inicial','Hora final','Data final','Resp. retrabalho','Local retrabalho','Observações','Data início','Peças OK','Peças refugadas','Fotos antes','Fotos depois'],q=function(v){return '"'+String(v==null?'':v).replace(/"/g,'""')+'"'};
var csv='\ufeff'+h.map(q).join(';')+'\n'+a.map(function(r){return [r.dt,r.cod,r.cli,r.prod,r.codCli,r.of,r.qtd,rtMatOf(r),r.mot,r.respE,r.locE,r.st,r.hi,r.hf,r.df,r.respR,r.locR,r.obs,r.di,r.qOk,r.qRef,(r.fa||[]).length,(r.fd||[]).length].map(q).join(';')}).join('\n');
var l=document.createElement('a');l.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));l.download='retrabalhos_'+anaToday()+'.csv';document.body.appendChild(l);l.click();setTimeout(function(){URL.revokeObjectURL(l.href);l.remove()},3000)}
